name: Flutter CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Instalar Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '>=3.18.0-18.0.pre.54'

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze código
        run: flutter analyze

      - name: Executar testes
        run: flutter test